syntax = "proto3";

option optimize_for = LITE_RUNTIME;

package tl.pro;

enum pk_cmd {
  none = 0;
  cmd_confirm = 100;
  cmd_verify = 101;

  cmd_player_max_value = 1000;
  cmd_player_float_value = 1001;
  cmd_player_bool_value = 1002;

  cmd_player_get_bag = 1100;
  cmd_get_item_name = 1101;
  cmd_set_item_type = 1102;
  cmd_set_item_pro = 1103;

  cmd_grab_world_item = 1200;

  cmd_auto_aim = 1300;
}

message packet {
  pk_cmd cmd = 1;
  optional bytes data = 2;
  int32 seq = 3;
}

message confirm {
  string message = 1;
  bool ok = 2;
  optional pk_cmd cmd = 3;
  optional bytes data = 4;
}